"""Core components: registry, base classes, exceptions."""
from audio_rag.core.registry import Registry
from audio_rag.core.base import (
    Word,
    TranscriptSegment,
    AudioChunk,
    SparseVector,
    EmbeddingResult,
    RetrievalResult,
    BaseASR,
    BaseDiarizer,
    BaseChunker,
    BaseEmbedder,
    BaseRetriever,
    BaseTTS,
)
from audio_rag.core.exceptions import (
    AudioRAGError,
    ConfigError,
    RegistryError,
    ResourceError,
    ASRError,
    DiarizationError,
    AlignmentError,
    EmbeddingError,
    RetrievalError,
    TTSError,
    PipelineError,
    GenerationError,
    RerankingError,
)

__all__ = [
    "Registry",
    "Word",
    "TranscriptSegment",
    "AudioChunk",
    "SparseVector",
    "EmbeddingResult",
    "RetrievalResult",
    "BaseASR",
    "BaseDiarizer",
    "BaseChunker",
    "BaseEmbedder",
    "BaseRetriever",
    "BaseTTS",
    "AudioRAGError",
    "ConfigError",
    "RegistryError",
    "ResourceError",
    "ASRError",
    "DiarizationError",
    "AlignmentError",
    "EmbeddingError",
    "RetrievalError",
    "TTSError",
    "PipelineError",
    "GenerationError",
    "RerankingError",
]
